Repository freeboardgames/FreeBoardGames.org, pull requests merged in 2019-06, with the labels that each got.

#250 Move nickname prompt into its own component
  src/App/Game/GameModePicker.test.tsx
  src/App/Lobby/ListPlayers.tsx
  src/App/Lobby/NicknamePrompt.tsx
  src/App/Lobby/Room.tsx
Labels: enhancement

#251 Allow users to change their nickname
  package.json
  src/App/Lobby/ListPlayers.test.tsx
  src/App/Lobby/ListPlayers.tsx
  src/App/Lobby/LobbyService.ts
  src/App/Lobby/NicknamePrompt.tsx
  src/App/Lobby/Room.tsx
  yarn.lock
Labels: enhancement

#254 Allow users to close the name prompt when they are editing their name
  src/App/Lobby/NicknamePrompt.tsx
  src/App/Lobby/Room.tsx
Labels: enhancement

#255 Move helpers into src/App/Helpers, add SSRHelper.isSSR()
  src/App/App.tsx
  src/App/Game/Game.tsx
  src/App/Helpers/AddressHelper.ts
  src/App/Helpers/SSRHelper.ts
  src/App/Lobby/LobbyService.ts
Labels: enhancement

#257 Share with QR code
  package.json
  src/App/Game/GameSharing.tsx
  src/App/Game/QrCodeIcon.test.tsx
  src/App/Game/QrCodeIcon.tsx
  src/App/Lobby/QrCodePopup.test.tsx
  src/App/Lobby/QrCodePopup.tsx
  yarn.lock
Labels: enhancement

#258 Add clickawaylistener to qrcodes
  src/App/Lobby/QrCodePopup.tsx
Labels: enhancement

#266 Fix yarn.lock from dependabot/npm_and_yarn/handlebars-4.1.2 #261, upgrade deps
  package.json
  yarn.lock
Labels: bug, dependencies, high priority

#271 Format @types/
  @types/@freeboardgame.org/index.d.ts
  @types/chess.js/index.d.ts
  @types/koa-no-cache/index.d.ts
  @types/static.d.ts
  package.json
Labels: enhancement

#270 Upgrade packages in package.json
  package.json
  yarn.lock
Labels: dependencies

#269 Improve metadata
  src/metadata.test.ts
  src/metadata.ts
Labels: dependencies

#273 Improve hot reloads (still does page refresh)
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: enhancement

#274 Revert " Improve hot reloads" #273
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: bug

#275 Fix hot reloads in cases where the SW is not installed
  package.json
  webpack.common.js
  webpack.dev.js
  yarn.lock
Labels: bug

#277 Fix #276
  src/App/Game/GameInstructions.tsx
Labels: bug

#279 Fix typography variant
  src/App/Game/GameDarkSublayout.tsx
Labels: bug, high priority

#281 Add extraCardContent for Tic-Tac-Toe, remove card from gameOver / improve design
  src/App/Game/GameOver.tsx
  src/games/tictactoe/board.tsx
Labels: enhancement

#289 Use material ui's typography in takesix
  src/games/takesix/PlayerHand.tsx
  src/games/takesix/ScoreBadges.css
  src/games/takesix/ScoreBadges.tsx
Labels: enhancement

#291 Fix webpack hot reload bug
  webpack.common.js
Labels: bug

#288 Automatically scroll to top of page on page load
  src/App/App.tsx
  src/App/ScrollToTop.tsx
Labels: enhancement

#296 Add Husky for pre-commit tests
  package.json
  yarn.lock
Labels: enhancement

#297 Fix 'Not implemented: window.scrollTo' warning in tests
  test/test-setup.js
Labels: bug

#299 Add testing scripts to package.json
  package.json
Labels: enhancement

#301 Fix memory leak in MessagePage
  src/App/MessagePageClass.test.tsx
  src/App/MessagePageClass.tsx
Labels: bug

#303 Import markdown files directly
  src/games/tictactoe/index.ts
  src/typings.d.ts
  webpack.common.js
  webpack.server.js
Labels: enhancement

#306 Rename TictactoeCustomScenario -> TakesixCustomScenario
  src/games/takesix/game.test.ts
Labels: bug

#305 Fix TS warning: Arbitrary expressions are forbidden in export assignments in ambient contexts
  src/typings.d.ts
Labels: enhancement

#304 Re-add `yarn run precommit` command accidentally removed in prior commit
  package.json
Labels: enhancement

#307 Add Seabattle text instructions
  src/games/seabattle/index.ts
  src/games/seabattle/instructions.md
Labels: enhancement

#309 Add Nine Mens Morris to README
  README.md
Labels: enhancement

#313 Use ttag for better i18n
  @types/@freeboardgame.org/index.d.ts
  i18n/applyi18n.bash
  i18n/cs.po
  i18n/cs.po.json
  i18n/en.po
  i18n/en.po.json
  i18n/updatei18ntemplates.bash
  package.json
  src/About/About.tsx
  src/App/App.ssr.test.tsx
  src/App/App.tsx
  src/App/MessagePageClass.tsx
  src/App/translations/cs.ts
  src/App/translations/en.ts
  src/App/translations/index.ts
  src/App/translations/pt.ts
  src/typings.d.ts
  test/test-setup.js
  yarn.lock
Labels: enhancement

#312 Use SSRHelper.isSSR() in App.tsx
  src/App/App.tsx
Labels: enhancement

#311 Cache builds the right way with webpack-dev-server
  i18n/cs.po.json
  i18n/en.po.json
  package.json
  test/test-setup.js
  webpack.dev.js
  webpack.server.js
  yarn.lock
Labels: enhancement

#314 .gitignore i18n/*.json
  .gitignore
  i18n/cs.po.json
  i18n/en.po.json
  package.json
  webpack.server.js
Labels: bug

#318 Make FreeBoardGame.org link in blog go to /
  blog/themes/next/layout/_partials/header.swig
Labels: enhancement

#319 Change order of games
  src/games/index.ts
Labels: enhancement

#321 reversi: penalty points -> score points
  src/games/reversi/Scoreboard.tsx
Labels: enhancement

#324 Add breadcrumbs support for SEO
  src/index.html
  src/metadata.ts
  src/server_fbg.tsx
Labels: enhancement

#327 Enable full hot reloading
  src/app.tsx
Labels: enhancement

#329 Format html, update server_fbg.tsx accordingly
  src/index.html
  src/server_fbg.tsx
Labels: housekeeping

#328 Run eslint for javascript in test/ and i18n/ too
  .eslintrc-javascript.js
  .eslintrc.js
  package.json
  test/stockfish8Mock.js
  test/test-setup.js
  test/test-shim.js
  yarn.lock
Labels: housekeeping

#330 Fix App.test.tsx (was actually testing our async loading page, not App.tsx...), increase coverage
  package.json
  src/App/App.ssr.test.tsx
  src/App/App.test.tsx
  yarn.lock
Labels: housekeeping

#332 Test lobby rename
  src/App/Lobby/LobbyService.test.tsx
Labels: housekeeping

#331 Use setImmediate() instead of wait-for-expect in App.test.tsx
  package.json
  src/App/App.test.tsx
  yarn.lock
Labels: housekeeping

#335 Upgrade packages: concurrently, pretty-quick, webpack, webpack-cli, webpack-dev-server
  package.json
  yarn.lock
Labels: dependencies

#336 Add .github/CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#337 Use pretty-lint to enforce codestyle, not eslint
  .eslintrc.js
  .travis.yml
  package.json
  yarn.lock
Labels: enhancement

#339 Fix precommit hook
  package.json
Labels: bug
