Repository freeboardgames/FreeBoardGames.org, pull requests merged in 2020-03, with the labels that each got.

#441 Hangman
  cypress/integration/Hangman.ts
  cypress/integration/TicTacToe.ts
  games/hangman/EnterWordPrompt.tsx
  games/hangman/board.tsx
  games/hangman/config.ts
  games/hangman/game.test.ts
  games/hangman/game.ts
  games/hangman/index.ts
  games/hangman/instructions.md
  games/hangman/media/thumbnail.png
  games/index.ts
Labels: enhancement

#449 More tests for Hangman
  cypress/integration/Hangman.ts
  games/hangman/board.tsx
Labels: enhancement

#455 Fix "Play Again" button for AI/Local games when offline
  components/App/Game/GameLayout.test.tsx
  components/App/Game/GameOver.tsx
  jest.unit.setup.ts
Labels: bug

#457 Fixes #452
  components/App/Game/GameOver.tsx
  e2e/__image_snapshots__/tic-tac-toe-test-ts-desktop-game-end-matches-golden-1-snap.png
  jest.e2e.setup.ts
Labels: duplicate

#456 Changing how we do the game list, fixes #452
  components/App/Game/GameCard.tsx
  components/App/GamesList.tsx
  e2e/__image_snapshots__/index-test-ts-desktop-matches-golden-1-snap.png
  e2e/__image_snapshots__/index-test-ts-mobile-matches-golden-1-snap.png
  e2e/__image_snapshots__/tic-tac-toe-test-ts-desktop-game-end-matches-golden-1-snap.png
  e2e/__image_snapshots__/tic-tac-toe-test-ts-mobile-game-end-matches-golden-1-snap.png
  pages/play/[gameCode]/GameInfo.tsx
Labels: bug

#459 Change layout of gameInfo again
  components/App/Game/GameModePicker.tsx
  jest.e2e.setup.ts
  pages/play/[gameCode]/GameInfo.tsx
Labels: enhancement
