Repository freeboardgames/FreeBoardGames.org, pull requests merged in 2020-04, with the labels that each got.

#467 Add reload button on "Failed to Fetch" page
  components/App/MessagePageClass.tsx
  pages/room/[gameCode]/[roomID]/Room.tsx
Labels: enhancement

#468 Game tests
  games/checkers/ai.test.ts
  games/checkers/board.test.tsx
  games/checkers/game.test.ts
  games/chess/ai.test.ts
  games/chess/ai.ts
  games/chess/board.test.tsx
  games/chess/game.test.ts
  games/chess/sound.test.ts
  games/common/Checkerboard.test.tsx
  games/cornerus/board.test.tsx
  games/cornerus/game.test.ts
  games/cornerus/game.ts
  games/fourinarow/board.test.tsx
  games/hangman/EnterWordPrompt.tsx
  games/hangman/board.tsx
  games/hangman/config.ts
  games/hangman/game.test.ts
  games/hangman/game.ts
  games/hangman/index.ts
  games/hangman/instructions.md
  games/hangman/media/thumbnail.png
  games/index.ts
  games/ninemensmorris/board.test.tsx
  games/ninemensmorris/game.test.ts
  games/ninemensmorris/game.ts
  games/ninemensmorris/piece.ts
  games/ninemensmorris/player.ts
  games/ninemensmorris/point.ts
  games/reversi/ai.test.ts
  games/reversi/ai.ts
  games/reversi/board.test.tsx
  games/reversi/game.test.ts
  games/seabattle/Battle.test.tsx
  games/seabattle/Radar.test.tsx
  games/seabattle/ShipsPlacement.test.tsx
  games/seabattle/ai.test.ts
  games/seabattle/ai.ts
  games/seabattle/board.test.tsx
  games/seabattle/sound.test.ts
  games/takesix/CardComponent.test.tsx
  games/takesix/ai.test.ts
  games/takesix/ai.ts
  games/takesix/board.test.tsx
  games/takesix/board.tsx
  games/takesix/game.test.ts
  games/takesix/game.ts
  games/tictactoe/ai.test.ts
  games/tictactoe/board.test.tsx
  games/tictactoeplus/ai.test.ts
  games/tictactoeplus/board.test.tsx
  jest.unit.config.js
Labels: bug, high priority

#471 Upgrade deps
  package.json
  yarn.lock
Labels: dependencies

#476 Use worker-loader in webpack.server.config.js
  webpack.server.config.js
Labels: enhancement

#477 Exclude workers in webpack.server.config.js
  webpack.server.config.js
Labels: enhancement

#475 Fix #464
  src/components/App/Game/GameLayout.test.tsx
  src/components/App/Game/GameOver.tsx
Labels: bug

#478 Upgrade deps
  package.json
  yarn.lock
Labels: dependencies

#486 Fix Reversi game over in local mode
  src/games/reversi/board.test.tsx
  src/games/reversi/board.tsx
Labels: bug

#488 Remove email button from GameSharing due to lack of use
  src/components/App/Game/GameSharing.test.tsx
  src/components/App/Game/GameSharing.tsx
Labels: enhancement

#485 Add visual cue of whose turn it is, add test for ScoreBadges
  jest.config.js
  package.json
  src/games/common/ScoreBadges.test.tsx
  src/games/common/ScoreBadges.tsx
  src/games/reversi/board.tsx
  src/games/takesix/board.tsx
  yarn.lock
Labels: enhancement

#489 Improve test coverage for GameInstructionsText.test.tsx
  src/components/App/Game/GameInstructionsText.test.tsx
Labels: housekeeping

#495 Increase test coverage
  jest.config.js
  package.json
  src/components/App/Game/GameInstructionsText.tsx
  src/components/App/Game/GameInstructionsVideo.test.tsx
  src/components/App/Game/GameInstructionsVideo.tsx
  src/components/App/ScrollToTop.test.tsx
  src/components/App/SelfXSSWarning.tsx
  src/components/App/Status.ts
  src/components/Breadcrumbs.test.tsx
  src/components/Header.test.tsx
  src/components/SEO.test.tsx
  src/components/SEO.tsx
  src/components/media/SvgError.tsx
  src/components/media/error.png
  src/components/media/fbg_logo_white_48.png
  src/components/media/loading.gif
  yarn.lock
Labels: housekeeping

#496 Remove unused files from src/ui
  src/ui/2d/card.css
  src/ui/2d/card.js
  src/ui/2d/card.test.js
  src/ui/2d/deck.css
  src/ui/2d/deck.js
  src/ui/2d/deck.test.js
  src/ui/2d/hex.js
  src/ui/2d/hex.test.js
  src/ui/2d/logo.js
  src/ui/2d/logo.test.js
  src/ui/2d/ui.js
  src/ui/2d/ui.ssr.test.js
  src/ui/2d/ui.test.js
  src/ui/3d/card.css
  src/ui/3d/card.js
  src/ui/3d/deck.css
  src/ui/3d/deck.js
  src/ui/3d/hex.js
  src/ui/3d/loading.css
  src/ui/3d/ui.js
  src/ui/card.js
  src/ui/deck.js
  src/ui/hex-utils.js
  src/ui/hex-utils.test.js
  src/ui/hex.js
  src/ui/ui.js
Labels: housekeeping

#501 Improve docker build with multi-stage builds, remove animations from blog
  Dockerfile
  blog/themes/next/_config.yml
Labels: enhancement

#507 Switch to data-testid for takesix board test
  src/components/App/Game/GameOver.tsx
  src/games/takesix/board.test.tsx
Labels: housekeeping

#498 Upgrade dependencies
  package.json
  yarn.lock
Labels: blocked, dependencies

#508 Add search for games
  cypress/integration/playAGame.ts
  src/components/App/FreeBoardGamesBar.test.tsx
  src/components/App/FreeBoardGamesBar.tsx
  src/components/App/Game/GameCard.tsx
  src/components/App/GamesList.test.tsx
  src/components/App/GamesList.tsx
  src/components/App/Helpers/AddressHelper.ts
  src/components/App/SearchBox.test.tsx
  src/components/App/SearchBox.tsx
  src/components/DesktopMobileView.tsx
  src/components/SEO.test.tsx
  src/helpers/tests.ts
  src/misc/UaContext.ts
  src/misc/UaHelper.ts
  src/pages/_app.tsx
  src/pages/room/[gameCode]/[roomID]/Room.tsx
Labels: enhancement

#512 Fix yarn run dev
  package.json
Labels: bug

#518 Upgrade deps
  Dockerfile
  package.json
  yarn.lock
Labels: dependencies

#525 Generate the blog with Node 13.13.0 because of Hexo incompatibility with Node 14
  Dockerfile
  blog/yarn.lock
Labels: bug, high priority

#523 Hangman: allow keyboard entry, remove extra ! from gameover ("you won!!")
  src/games/hangman/EnterWordPrompt.tsx
  src/games/hangman/board.tsx
Labels: enhancement

#527 Upgrade deps
  package.json
  yarn.lock
Labels: dependencies
